### ISSUE TITLE
Sort out fibers node package in the bundle process

### ISSUE THREAD

**Issue by ovidiuch** [ovidiuch/aufond#48]
The last time it gave an error on the Turtle instance, maybe due to some update it is no longer needed

**Comment by ovidiuch** [comment]
On Turtle backup instance it can't create bundle because it fails and upgrading fibers package

```
npm WARN package.json kexec@0.1.1 homepage field must be a string url. Deleted.
npm WARN package.json progress@0.0.5 No repository field.
npm WARN package.json uglify-js@2.2.5 No repository field.
npm WARN package.json uglify-js@2.2.5 'repositories' (plural) Not supported.
npm WARN package.json Please pick one as the 'repository' field
npm http GET https://registry.npmjs.org/fibers
npm http 304 https://registry.npmjs.org/fibers

> fibers@1.0.1 install /var/www/aufond/.bundle/server/node_modules/fibers
> node ./build.js

gyp ERR! configure error
gyp ERR! stack Error: "pre" versions of node cannot be installed, use the --nodedir flag instead
gyp ERR! stack     at install (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:69:16)
gyp ERR! stack     at Object.self.commands.(anonymous function) [as install] (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/node-gyp.js:56:37)
gyp ERR! stack     at getNodeDir (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:219:20)
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:105:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:635:7)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:103:17)
gyp ERR! stack     at maybeClose (child_process.js:735:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:802:5)
gyp ERR! System Linux 3.2.0-4-amd64
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /var/www/aufond/.bundle/server/node_modules/fibers
gyp ERR! node -v v0.11.3-pre
gyp ERR! node-gyp -v v0.9.6
gyp ERR! not ok
Build failed
npm ERR! weird error 1
npm ERR! not ok code 0
```

It might seem to be a permission problem but it doesn't work with root as well

**Comment by ovidiuch** [comment]
It is still needed. But we will rebuild the installation script anyway, in #49, and we'll see if this replicates there
